package br.com.marrs.ischool.entidades;


/**
 * DeviceRegId generated by hbm2java
 */

public class DeviceRegId  implements Entidade{


	/**
	 * 
	 */
	private static final long serialVersionUID = 1120995083145836686L;


    private Long idReg;
    

	private Device device;
   
    private String regid;
    
  
	private Usuario usuario;

	@Override
	public Long getId() {
		
		return this.getIdReg();
	}

	@Override
	public void setId(Long id) {
		this.setIdReg(id);
		
	}
	
	

	public Long getIdReg() {
		return idReg;
	}

	public void setIdReg(Long idReg) {
		this.idReg = idReg;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Device getDevice() {
		return device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public String getRegid() {
		return regid;
	}

	public void setRegid(String regid) {
		this.regid = regid;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idReg == null) ? 0 : idReg.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceRegId other = (DeviceRegId) obj;
		if (idReg == null) {
			if (other.idReg != null)
				return false;
		} else if (!idReg.equals(other.idReg))
			return false;
		return true;
	}



}


