package br.com.marrs.ischool.entidades;


import java.util.List;

/**
 * Device generated by hbm2java
 */

public class Device  implements Entidade {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1067018112337109746L;
	

	private Long idDevice;
	
   
    private String device;
       
	private List<DeviceRegId> deviceRegIds;

    
    public String getDevice() {
        return this.device;
    }
    
    public void setDevice(String device) {
        this.device = device;
    }

	public List<DeviceRegId> getDeviceRegIds() {
		return deviceRegIds;
	}

	public void setDeviceRegIds(List<DeviceRegId> deviceRegIds) {
		this.deviceRegIds = deviceRegIds;
	}

	@Override
	public Long getId() {
		return getIdDevice();
	}

	@Override
	public void setId(Long id) {
		this.setIdDevice(id);		
	}

	public Long getIdDevice() {
		return idDevice;
	}

	public void setIdDevice(Long idDevice) {
		this.idDevice = idDevice;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idDevice == null) ? 0 : idDevice.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Device other = (Device) obj;
		if (idDevice == null) {
			if (other.idDevice != null)
				return false;
		} else if (!idDevice.equals(other.idDevice))
			return false;
		return true;
	}




}


